### ISSUE TITLE
Can't move robot using IKFast for fanuc_lrmate200id

### ISSUE THREAD

**Issue by cvanclee** [ros-industrial/fanuc_experimental#30]
I'm opening moveit setup with
>roslaunch moveit_setup_assistant setup_assistant.launch

and clicking edit existing package. I load fanuc_lrmate200id_moveit_config. Then I click Planning Groups, then manipulator, then edit selected, and choose fanuc_lrmate200id_manipulator_kinematics/IKFastKinematicsPlugin for the Kinematic Solver. I then press Save, go to Configuration Files, and hit Generate Package. I run catkin_make, and open RViz with
>roslaunch fanuc_lrmate200id_moveit_config demo.launch

which results in the robot being loaded on my screen normally, but I can't move it by clicking it or by running code to move it. Using KDLKinematicsPlugin works fine for me, but I would like to use IKFast

**Comment by gavanderhoorn** [comment]
Can you tell me why you edit the MoveIt configuration? The IKFast plugin is generated code, and cannot be used with anything but the original chain that it was generated for.

Please see [Tool0 URDF Modifications Break Path Planning](http://answers.ros.org/question/256429) for a (probably) related ROS Answers Q&A.

**Comment by cvanclee** [comment]
I edited the configuration to add a tool to the end of the robot. I made a link_7 and a joint_7. Joint_7 is connected via link_6 and link_7. Then I connected link_7 to tool0. To keep the baselink->tool0 rule, should I instead connect tool0-link7 for joint_7? Thanks for the help

**Comment by gavanderhoorn** [comment]
No, I'm afraid you can't change the `base_link->tool0` chain, or the IKFast plugin won't work any more.

I would also not recommend to introduce a `joint_7` or a `link_7`, as it seems like something that can become confusing (seeing as all the links and joints in the robot model are named in that fashion).

If you need a toolframe, I recommend making it a child of the `flange` frame that was recently added to all models (11ae75b0). Don't change `tool0`, as it's not meant to be changed. To plan for your new toolframe, you could either see whether you could configure it as a new end effector in the MoveIt configuration, or you could just transform any pose target you want to plan for back to `tool0` first - if you want to stick with the IKFast plugin.

Using any other plugin for the new chain that you would define would probably be easier.

---

Edit: the various tutorials and wiki pages do tell you to make new tool frames children of `tool0`, but we're moving away from that, and the introduction of the `flange` frames is the first step. See also ros-industrial/fanuc#213.

Also: if you haven't already: I would recommend to create a new xacro macro to add the tool frame joint and link, instead of editing `fanuc_lrmate200id_macro.xacro` and add it there directly. That would cleanly compose things and keep the separation of concerns, while also making it easier for you to keep track of updates/changes upstream (ie: in this repository).

**Comment by cvanclee** [comment]
I cloned the latest version of fanuc_experimental to get the flange updates. So, just to be clear, I should make a new link for my tool, then make a new joint with the parent link as flange and the child link as my tool? If so, thanks for the help!

**Comment by gavanderhoorn** [comment]
@cvanclee wrote:
> I should make a new link for my tool, then make a new joint with the parent link as flange and the child link as my tool?

yes, you could do that yes.

But make sure to give your tool frame the correct orientation: `flange` follows ROS conventions, so x+ is forward. Tools on Fanucs have z+ forward, which requires the `pi -pi/2.0 0` rotations that the `tool0` joint has.

And note that you still cannot use the IKFast plugin with your new tool, unless you setup MoveIt properly *or* manually transform poses for your new tool back to `tool0` (which is possible, as there is a `your_tool->tool0` transform via `flange` available).
