### ISSUE TITLE
Connection problems with the fanuc_lrmate200id

### ISSUE THREAD

**Issue by cvanclee** [ros-industrial/fanuc_experimental#32]
I'm having connection issues while connecting my laptop running ROS/MoveIt to the physical robot to run movement commands. I'm not sure whether I've configured something wrong or there is a network issue. Attempts to connect to the physical robot only go through about 1/3 of the time, and there's a small chance I'll get disconnected while running my movement commands. Sometimes the robot seems to connect, and RViz will update to match the physical robot's position, but move commands don't reach the robot. Other times, the connection isn't made at all.

Here's the output from the teach pendant, I'm not sure how useful this is:

![imag0324](https://user-images.githubusercontent.com/22084533/28213462-22291c8c-6874-11e7-8ee5-2f8b312ec21b.jpg)

I also occasionally get this error in my console

`Failed to connect to server, rc: -1. Error: 'Transport endpoint is already connected'`

**Comment by gavanderhoorn** [comment]
This definitely looks like a network issue.

Are you using a wireless connection by any chance? If so, try with a wired one.

**Comment by gavanderhoorn** [comment]
PS: could I ask you to open issues about `fanuc` pkgs over at `ros-industrial/fanuc`'s issue tracker btw? I try to keep things centralised, and this repo is just for storage of packages.

We can keep this one open for now, but please keep it in mind next time.

Thanks.

**Comment by cvanclee** [comment]
I tried switching to a wired connection, it results in the same issues. Might it better to talk to my network managers about this? Sorry, I didn't realize that belonged in the fanuc issues

**Comment by gavanderhoorn** [comment]
Assuming that the software has not changed, it would seem likely that this is a network issue. If possible, try different network cables (both between you and the network, and between the controller and the network), or even a direct connection (also with different cables).

From the errors on the TP, it looks like connections are dropping (`67211` and `67212` are `HOST-211` and `HOST-212`, `Connection Write Buffer is full` and `Write Direction shut down by Peer` respectively). The error on your terminal also suggests this.

I typically see these when cables have gone bad or there is intermittent network connectivity because of some other reason.

Check that the ROS nodes involved aren't repeatedly shutting down and coming back up.

If that is not the case, I'd look at the hardware side of things (ie: your network).

**Comment by cvanclee** [comment]
I'll try a direct connection between by laptop and the robot, my cable is definitely good. If that works, I'll assume its a network issue and talk to the network managers. Thanks!
