### ISSUE TITLE
OPW kinematic parameters

### ISSUE THREAD

**Issue by marip8** [ros-industrial/fanuc_experimental#61]
Would it be beneficial to store OPW kinematic parameters in a file in the support packages for robot variants? They're not necessarily hard to set up (and the [MoveIt OPW kinematics plugin](https://github.com/JeroenDM/moveit_opw_kinematics_plugin) has some helpful sanity checks for the parameters now), but it can be a bit confusing for those not familiar with the parameters or the means of figuring out what the parameters should be.

**Comment by gavanderhoorn** [comment]
We've already done that for some support packages over in `ros-industrial/fanuc`. See https://github.com/ros-industrial/fanuc/pull/284 (and https://github.com/ros-industrial/fanuc/pull/293).

So: yes, we can do that, and we already have that in place for others.

**Comment by gavanderhoorn** [comment]
Example: [fanuc_lrmate200ib_support/config/opw_parameters_lrmate200ib.yaml](https://github.com/ros-industrial/fanuc/blob/e70631ed15e3d253b7216dcd351a6d3708c84b5b/fanuc_lrmate200ib_support/config/opw_parameters_lrmate200ib.yaml)

**Comment by marip8** [comment]
Fantastic; I'll close this issue since it's already been addressed. I have the parameters for the R2000iC165F; I can add those in a PR with the 125L variant. Is there a convenient way to reference this file in a MoveIt `kinematics.yaml` file, or would this just be for reference?

**Comment by gavanderhoorn** [comment]
> I have the parameters for the R2000iC165F; I can add those in a PR with the 125L variant.

Could you please submit those in a separate PR? That way we keep PRs on-topic as much as possible.

>  Is there a convenient way to reference this file in a MoveIt `kinematics.yaml` file, or would this just be for reference?

Since https://github.com/ros-planning/moveit/pull/1997 there is: in the UI of the MSA you can specify an "additional file" to load whatever parameters you need, which gets added to [planning_context.launch](https://github.com/ros-planning/moveit/pull/1997/files#diff-36ea4bbfc4da166cba5c1d266e9c64fd95789c91100e7ca1fffef03253f303fc).

If you have an existing MoveIt configuration pkg, you could just add the `<rosparam command="load" file="$(find <your_pkg>)/config/opw_parameters_<variant>.yaml"/>` line yourself in that file in the same place.
